# Generated by Django 4.2.7 on 2025-06-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tipo',
            field=models.CharField(choices=[('site', 'Site'), ('bot_ia', 'Bot com IA'), ('bot_padrao', 'Bot sem IA'), ('sheets', 'Envio via Google Sheets')], default='site', max_length=20, verbose_name='Tipo de Projeto'),
        ),
    ]
